import React, { useState, useRef, useEffect } from 'react';
import axios from 'axios';
import { getAiUrl, getChatMemoryUrl } from '../config';
import './Chatbot.css';

const Chatbot = () => {
    // UI State: isOpen (window visibility), view ('chat' for active conversation, 'history' for list)
    const [isOpen, setIsOpen] = useState(false);
    const [view, setView] = useState('chat'); 
    
    // Session State: selectedChatId tracks which persistent conversation we are currently using.
    const [selectedChatId, setSelectedChatId] = useState(null);
    const [chatList, setChatList] = useState([]);
    const [messages, setMessages] = useState([
        { role: 'assistant', text: 'Hello! I am your AI assistant with memory. I can remember our past conversations.' }
    ]);
    const [input, setInput] = useState('');
    const [loading, setLoading] = useState(false);
    const chatEndRef = useRef(null);

    const toggleChat = () => setIsOpen(!isOpen);

    // Automatically scroll to the latest message whenever messages array updates.
    const scrollToBottom = () => {
        chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
    };

    useEffect(() => {
        if (isOpen) {
            scrollToBottom();
        }
    }, [messages, isOpen]);

    // Fetch the list of past conversation sessions whenever the user opens the history view.
    useEffect(() => {
        if (isOpen && view === 'history') {
            fetchChatList();
        }
    }, [isOpen, view]);

    /**
     * API Call: Retrieves metadata (IDs and descriptions) for all chats owned by the user.
     */
    const fetchChatList = async () => {
        try {
            const token = localStorage.getItem('token');
            const response = await axios.get(getChatMemoryUrl(), {
                headers: { Authorization: `Bearer ${token}` }
            });
            setChatList(response.data);
        } catch (error) {
            console.error("Error fetching chat history:", error);
        }
    };

    /**
     * API Call: Loads the detailed message history for a specific chat ID from the database.
     */
    const loadChat = async (chatId) => {
        setLoading(true);
        setView('chat'); // Switch to chat view after loading
        setSelectedChatId(chatId);
        try {
            const token = localStorage.getItem('token');
            const response = await axios.get(`${getChatMemoryUrl()}/${chatId}`, {
                headers: { Authorization: `Bearer ${token}` }
            });
            // Reformat backend message types (USER/ASSISTANT) to frontend role naming
            const formattedMessages = response.data.map(m => ({
                role: m.type.toLowerCase(),
                text: m.content
            }));
            setMessages(formattedMessages);
        } catch (error) {
            console.error("Error loading chat:", error);
            setMessages([{ role: 'assistant', text: "Error loading conversation history." }]);
        } finally {
            setLoading(false);
        }
    };

    /**
     * Resets the UI to a clean slate for a brand-new conversation.
     * The new chatId will be generated by the backend on the first message sent.
     */
    const startNewChat = () => {
        setSelectedChatId(null);
        setMessages([{ role: 'assistant', text: 'Started a new conversation. How can I help you today?' }]);
        setView('chat');
    };

    /**
     * Main handler for sending messages. 
     * Handles both 'Start New Session' and 'Continue Session' logic.
     */
    const handleSend = async (e) => {
        e.preventDefault();
        if (!input.trim()) return;

        const userMsg = { role: 'user', text: input };
        setMessages(prev => [...prev, userMsg]);
        const currentInput = input;
        setInput('');
        setLoading(true);

        try {
            const token = localStorage.getItem('token');
            let response;
            
            if (!selectedChatId) {
                // Scenario: First message of a new conversation.
                // Call /start to create a database entry and get a generated description.
                response = await axios.post(`${getChatMemoryUrl()}/start`,
                    { message: currentInput },
                    { headers: { Authorization: `Bearer ${token}` } }
                );
                setSelectedChatId(response.data.chatId);
                const botMsg = { role: 'assistant', text: response.data.message || "No response received." };
                setMessages(prev => [...prev, botMsg]);
            } else {
                // Scenario: Continuing an existing session.
                // Send the chatId so the Spring AI backend retrieves the context from JDBC.
                response = await axios.post(`${getChatMemoryUrl()}/${selectedChatId}`,
                    { message: currentInput },
                    { headers: { Authorization: `Bearer ${token}` } }
                );
                const botMsg = { role: 'assistant', text: response.data.content || "No response received." };
                setMessages(prev => [...prev, botMsg]);
            }
        } catch (error) {
            console.error("Chat error:", error);
            setMessages(prev => [...prev, { role: 'assistant', text: "Sorry, I am having trouble connecting to the system right now." }]);
        } finally {
            setLoading(false);
        }
    };

    return (
        <>
            {/* Main floating action button to open the chatbot */}
            <button className="chatbot-toggle" onClick={toggleChat}>
                💬 AI Assistant
            </button>

            {/* Main Chat Interface */}
            {isOpen && (
                <div className="chatbot-window card fade-in">
                    <div className="chatbot-header">
                        <div className="header-title">
                            <h4>Medical AI</h4>
                            {/* Visual indicator that context is being remembered for the current session */}
                            {selectedChatId && <small>Memory Active</small>}
                        </div>
                        <div className="header-actions">
                            {/* Toggle between Chat View and History List */}
                            <button onClick={() => setView(view === 'chat' ? 'history' : 'chat')} title="History" className="icon-btn">
                                {view === 'chat' ? '🕒' : '💬'}
                            </button>
                            {/* Start New Session button */}
                            <button onClick={startNewChat} title="New Chat" className="icon-btn">➕</button>
                            <button onClick={toggleChat} className="close-btn">×</button>
                        </div>
                    </div>

                    {view === 'chat' ? (
                        <>
                            {/* Active Chat Messages */}
                            <div className="chatbot-messages">
                                {messages.map((msg, index) => (
                                    <div key={index} className={`chat-message ${msg.role}`}>
                                        <div className="message-bubble">{msg.text}</div>
                                    </div>
                                ))}
                                {loading && (
                                    <div className="chat-message assistant">
                                        <div className="message-bubble loading">Thinking...</div>
                                    </div>
                                )}
                                <div ref={chatEndRef} />
                            </div>

                            {/* Input Form */}
                            <form onSubmit={handleSend} className="chatbot-input">
                                <input
                                    type="text"
                                    value={input}
                                    onChange={(e) => setInput(e.target.value)}
                                    placeholder="Ask me something..."
                                    disabled={loading}
                                />
                                <button type="submit" disabled={loading || !input.trim()}>Send</button>
                            </form>
                        </>
                    ) : (
                        /* History View: List of past conversations */
                        <div className="chatbot-history">
                            <h5>Past Conversations</h5>
                            {chatList.length === 0 ? (
                                <p className="empty-msg">No history found.</p>
                            ) : (
                                <div className="history-list">
                                    {chatList.map(chat => (
                                        <div key={chat.id} className="history-item" onClick={() => loadChat(chat.id)}>
                                            <span className="chat-desc">{chat.description || "Untitled Chat"}</span>
                                            <span className="chat-id">{chat.id.substring(0, 8)}...</span>
                                        </div>
                                    ))}
                                </div>
                            )}
                        </div>
                    )}
                </div>
            )}

        </>
    );
};

export default Chatbot;
